//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;

namespace EnterERP.Module.BusinessObjects.maptooni_CFSCustomers
{

    [DefaultClassOptions]
    [NavigationItem("CFSPOS")]
    public partial class BillingHistory : XPLiteObject
    {
        string fROID;
        [Size(120)]
        public string ROID
        {
            get { return fROID; }
            set { SetPropertyValue<string>("ROID", ref fROID, value); }
        }
        string fBillingPeriod;
        [Size(120)]
        public string BillingPeriod
        {
            get { return fBillingPeriod; }
            set { SetPropertyValue<string>("BillingPeriod", ref fBillingPeriod, value); }
        }
        string fAmount;
        [Size(120)]
        public string Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<string>("Amount", ref fAmount, value); }
        }
        string fbillingID;
        [Key]
        [Size(120)]
        public string billingID
        {
            get { return fbillingID; }
            set { SetPropertyValue<string>("billingID", ref fbillingID, value); }
        }
        string fpaymentType;
        [Size(30)]
        public string paymentType
        {
            get { return fpaymentType; }
            set { SetPropertyValue<string>("paymentType", ref fpaymentType, value); }
        }
        string fApprovalNumber;
        [Size(30)]
        public string ApprovalNumber
        {
            get { return fApprovalNumber; }
            set { SetPropertyValue<string>("ApprovalNumber", ref fApprovalNumber, value); }
        }
        public BillingHistory(Session session) : base(session) { }
    }

}
