//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;
using EnterERP.Module.BusinessObjects.CFSDealers.maptooni_CFSDealers;

namespace EnterERP.Module.BusinessObjects.maptooni_CFSCustomers
{
    [DefaultClassOptions]
    [NavigationItem("CFSPOS")]
    public partial class ccPayments : XPLiteObject
    {
        DSettings fROID;

        public DSettings ROID
        {
            get { return fROID; }
            set { SetPropertyValue<DSettings>("ROID", ref fROID, value); }
        }
        string fPaymentMethod;
        [Size(10)]
        public string PaymentMethod
        {
            get { return fPaymentMethod; }
            set { SetPropertyValue<string>("PaymentMethod", ref fPaymentMethod, value); }
        }
        string fAccountNumber;
        [Size(80)]
        public string AccountNumber
        {
            get { return fAccountNumber; }
            set { SetPropertyValue<string>("AccountNumber", ref fAccountNumber, value); }
        }
        string fexpdateMonth;
        [Size(10)]
        public string expdateMonth
        {
            get { return fexpdateMonth; }
            set { SetPropertyValue<string>("expdateMonth", ref fexpdateMonth, value); }
        }
        string fexpdateYear;
        [Size(10)]
        public string expdateYear
        {
            get { return fexpdateYear; }
            set { SetPropertyValue<string>("expdateYear", ref fexpdateYear, value); }
        }
        string fcvv;
        [Size(10)]
        public string cvv
        {
            get { return fcvv; }
            set { SetPropertyValue<string>("cvv", ref fcvv, value); }
        }
        string fNameOnAccount;
        [Size(80)]
        public string NameOnAccount
        {
            get { return fNameOnAccount; }
            set { SetPropertyValue<string>("NameOnAccount", ref fNameOnAccount, value); }
        }
        string flastFourDigits;
        [Size(4)]
        public string lastFourDigits
        {
            get { return flastFourDigits; }
            set { SetPropertyValue<string>("lastFourDigits", ref flastFourDigits, value); }
        }
        string ftype;
        [Size(10)]
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>("type", ref ftype, value); }
        }
        string faddrress;
        [Size(300)]
        public string addrress
        {
            get { return faddrress; }
            set { SetPropertyValue<string>("addrress", ref faddrress, value); }
        }
        string fcity;
        [Size(120)]
        public string city
        {
            get { return fcity; }
            set { SetPropertyValue<string>("city", ref fcity, value); }
        }
        string fstate;
        [Size(10)]
        public string state
        {
            get { return fstate; }
            set { SetPropertyValue<string>("state", ref fstate, value); }
        }
        string fzip;
        [Size(20)]
        public string zip
        {
            get { return fzip; }
            set { SetPropertyValue<string>("zip", ref fzip, value); }
        }
        string fphone;
        [Size(20)]
        public string phone
        {
            get { return fphone; }
            set { SetPropertyValue<string>("phone", ref fphone, value); }
        }
        bool factive;
        [Size(1)]
        public bool active
        {
            get { return factive; }
            set { SetPropertyValue<bool>("active", ref factive, value); }
        }

        DateTime dateActive;
        public DateTime DateActive
        {
            get
            {
                return dateActive;
            }
            set
            {
                SetPropertyValue("DateActive", ref dateActive, value);
            }
        }

        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        public ccPayments(Session session) : base(session) { }
    }

}
