//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;

namespace EnterERP.Module.BusinessObjects.maptooni_CFSCustomers
{
    [DefaultClassOptions]
    [NavigationItem("CFSPOS")]
    [DefaultProperty("ROID")]
    public partial class Dealers : XPLiteObject
    {
        string fcfsUserName;
        [Size(120)]
        public string cfsUserName
        {
            get { return fcfsUserName; }
            set { SetPropertyValue<string>("cfsUserName", ref fcfsUserName, value); }
        }
        string fcfsPassWord;
        [Size(120)]
        public string cfsPassWord
        {
            get { return fcfsPassWord; }
            set { SetPropertyValue<string>("cfsPassWord", ref fcfsPassWord, value); }
        }
        string fLegalName;
        [Size(250)]
        public string LegalName
        {
            get { return fLegalName; }
            set { SetPropertyValue<string>("LegalName", ref fLegalName, value); }
        }
        string fROID;
        [Key]
        public string ROID
        {
            get { return fROID; }
            set { SetPropertyValue<string>("ROID", ref fROID, value); }
        }
        string fFName;
        [Size(120)]
        public string FName
        {
            get { return fFName; }
            set { SetPropertyValue<string>("FName", ref fFName, value); }
        }
        string fMi;
        [Size(1)]
        public string Mi
        {
            get { return fMi; }
            set { SetPropertyValue<string>("Mi", ref fMi, value); }
        }
        string fLName;
        [Size(120)]
        public string LName
        {
            get { return fLName; }
            set { SetPropertyValue<string>("LName", ref fLName, value); }
        }
        string fAddress_b;
        [Size(120)]
        public string Address_b
        {
            get { return fAddress_b; }
            set { SetPropertyValue<string>("Address_b", ref fAddress_b, value); }
        }
        string fAddress2_b;
        [Size(120)]
        public string Address2_b
        {
            get { return fAddress2_b; }
            set { SetPropertyValue<string>("Address2_b", ref fAddress2_b, value); }
        }
        string fCity_b;
        [Size(120)]
        public string City_b
        {
            get { return fCity_b; }
            set { SetPropertyValue<string>("City_b", ref fCity_b, value); }
        }
        string fState_b;
        [Size(10)]
        public string State_b
        {
            get { return fState_b; }
            set { SetPropertyValue<string>("State_b", ref fState_b, value); }
        }
        string fZip_b;
        [Size(5)]
        public string Zip_b
        {
            get { return fZip_b; }
            set { SetPropertyValue<string>("Zip_b", ref fZip_b, value); }
        }
        string fphone_b;
        [Size(15)]
        public string phone_b
        {
            get { return fphone_b; }
            set { SetPropertyValue<string>("phone_b", ref fphone_b, value); }
        }
        string ftype_phone_b;
        [Size(20)]
        public string type_phone_b
        {
            get { return ftype_phone_b; }
            set { SetPropertyValue<string>("type_phone_b", ref ftype_phone_b, value); }
        }
        string fAddress_d;
        [Size(120)]
        public string Address_d
        {
            get { return fAddress_d; }
            set { SetPropertyValue<string>("Address_d", ref fAddress_d, value); }
        }
        string fAddress2_d;
        [Size(120)]
        public string Address2_d
        {
            get { return fAddress2_d; }
            set { SetPropertyValue<string>("Address2_d", ref fAddress2_d, value); }
        }
        string fCity_d;
        [Size(120)]
        public string City_d
        {
            get { return fCity_d; }
            set { SetPropertyValue<string>("City_d", ref fCity_d, value); }
        }
        string fState_d;
        [Size(10)]
        public string State_d
        {
            get { return fState_d; }
            set { SetPropertyValue<string>("State_d", ref fState_d, value); }
        }
        string fZip_d;
        [Size(5)]
        public string Zip_d
        {
            get { return fZip_d; }
            set { SetPropertyValue<string>("Zip_d", ref fZip_d, value); }
        }
        string fphone_d;
        [Size(15)]
        public string phone_d
        {
            get { return fphone_d; }
            set { SetPropertyValue<string>("phone_d", ref fphone_d, value); }
        }
        string ftype_phone_d;
        [Size(20)]
        public string type_phone_d
        {
            get { return ftype_phone_d; }
            set { SetPropertyValue<string>("type_phone_d", ref ftype_phone_d, value); }
        }
        public Dealers(Session session) : base(session) { }
    }

}
