//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Base;

namespace EnterERP.Module.BusinessObjects.maptooni_CFSCustomers
{
    [DefaultClassOptions]
    [NavigationItem("CFSPOS")]
    public partial class Devices : XPLiteObject
    {
        string fROID;
        [Size(40)]
        public string ROID
        {
            get { return fROID; }
            set { SetPropertyValue<string>("ROID", ref fROID, value); }
        }
        string fDeviceName;
        [Size(120)]
        public string DeviceName
        {
            get { return fDeviceName; }
            set { SetPropertyValue<string>("DeviceName", ref fDeviceName, value); }
        }
        string fmacaddress;
        [Key]
        [Size(140)]
        public string macaddress
        {
            get { return fmacaddress; }
            set { SetPropertyValue<string>("macaddress", ref fmacaddress, value); }
        }
        string factive;
        [Size(1)]
        public string active
        {
            get { return factive; }
            set { SetPropertyValue<string>("active", ref factive, value); }
        }
        string fdeviceType;
        [Size(10)]
        public string deviceType
        {
            get { return fdeviceType; }
            set { SetPropertyValue<string>("deviceType", ref fdeviceType, value); }
        }
        string fiosSerialNumber;
        [Size(200)]
        public string iosSerialNumber
        {
            get { return fiosSerialNumber; }
            set { SetPropertyValue<string>("iosSerialNumber", ref fiosSerialNumber, value); }
        }
        public Devices(Session session) : base(session) { }
    }

}
